#!/bin/bash

# =================配置管理=================

# 加载配置
_load_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        cat > "$CONFIG_FILE" <<EOF
REST_GAP=$DEFAULT_REST_GAP
LOOK_AWAY=$DEFAULT_LOOK_AWAY
SOUND_START=$DEFAULT_SOUND_START
SOUND_END=$DEFAULT_SOUND_END
SOUND_SWITCH=$DEFAULT_SOUND_SWITCH
LANGUAGE=$DEFAULT_LANGUAGE
EYE_MODE=$DEFAULT_EYE_MODE
EOF
    fi
    source "$CONFIG_FILE"
    
    # 确保变量有默认值 (防止旧配置文件缺失新变量)
    REST_GAP=${REST_GAP:-$DEFAULT_REST_GAP}
    LOOK_AWAY=${LOOK_AWAY:-$DEFAULT_LOOK_AWAY}
    SOUND_START=${SOUND_START:-$DEFAULT_SOUND_START}
    SOUND_END=${SOUND_END:-$DEFAULT_SOUND_END}
    SOUND_SWITCH=${SOUND_SWITCH:-$DEFAULT_SOUND_SWITCH}
    LANGUAGE=${LANGUAGE:-$DEFAULT_LANGUAGE}
    EYE_MODE=${EYE_MODE:-$DEFAULT_EYE_MODE}

    [ -f "$CUSTOM_SOUNDS_MAP" ] && source "$CUSTOM_SOUNDS_MAP"
}

# 保存基础配置
_save_config() {
    cat > "$CONFIG_FILE" <<EOF
REST_GAP=${REST_GAP:-$DEFAULT_REST_GAP}
LOOK_AWAY=${LOOK_AWAY:-$DEFAULT_LOOK_AWAY}
SOUND_START=${SOUND_START:-$DEFAULT_SOUND_START}
SOUND_END=${SOUND_END:-$DEFAULT_SOUND_END}
SOUND_SWITCH=${SOUND_SWITCH:-$DEFAULT_SOUND_SWITCH}
LANGUAGE=${LANGUAGE:-$DEFAULT_LANGUAGE}
EYE_MODE=${EYE_MODE:-$DEFAULT_EYE_MODE}
EOF
}
