#!/bin/bash

# =================配置管理 (v2.0)=================

# 默认全局配置
DEFAULT_GLOBAL_QUIET="off"
DEFAULT_ROOT_CMD="help"
DEFAULT_SOUND_SWITCH="on"
DEFAULT_LANGUAGE="en"

# 加载全局配置 (eye.conf)
_load_global_config() {
    if [ ! -f "$CONFIG_FILE" ]; then
        # 生成默认全局配置
        cat > "$CONFIG_FILE" <<EOF
GLOBAL_QUIET=$DEFAULT_GLOBAL_QUIET
ROOT_CMD=$DEFAULT_ROOT_CMD
SOUND_SWITCH=$DEFAULT_SOUND_SWITCH
LANGUAGE=$DEFAULT_LANGUAGE
EOF
    fi
    
    source "$CONFIG_FILE"
    
    # 确保变量有默认值
    GLOBAL_QUIET=${GLOBAL_QUIET:-$DEFAULT_GLOBAL_QUIET}
    ROOT_CMD=${ROOT_CMD:-$DEFAULT_ROOT_CMD}
    SOUND_SWITCH=${SOUND_SWITCH:-$DEFAULT_SOUND_SWITCH}
    LANGUAGE=${LANGUAGE:-$DEFAULT_LANGUAGE}

    # 加载自定义音效映射
    [ -f "$CUSTOM_SOUNDS_MAP" ] && source "$CUSTOM_SOUNDS_MAP"
}

# 保存全局配置
_save_global_config() {
    cat > "$CONFIG_FILE" <<EOF
GLOBAL_QUIET=${GLOBAL_QUIET:-$DEFAULT_GLOBAL_QUIET}
ROOT_CMD=${ROOT_CMD:-$DEFAULT_ROOT_CMD}
SOUND_SWITCH=${SOUND_SWITCH:-$DEFAULT_SOUND_SWITCH}
LANGUAGE=${LANGUAGE:-$DEFAULT_LANGUAGE}
EOF
}

